{% set name = "hookee" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 752548a5ae4803b5b1a3e70b7f3fdd99595a52dfce11f6ee8c92f50ba2e5247d

build:
  noarch: python
  entry_points:
    - hookee=hookee.cli:hookee
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - pyngrok
    - python-dotenv
    - flask

test:
  imports:
    - hookee
  commands:
    - pip check
    - hookee --help
  requires:
    - pip

about:
  home: https://github.com/alexdlaird/hookee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line webhooks, on demand
  description: |
    hookee is a simple command line utility which generates webhooks on demand and dumps useful information
    to the console when requests are sent to those endpoints.
  dev_url: https://github.com/alexdlaird/hookee

extra:
  recipe-maintainers:
    - alexdlaird
