{% set name = "hookee" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 571c30be2f5214f1499d935742b7fbf280d89b6c9c51214987a92472b8d7d04c

build:
  noarch: python
  entry_points:
    - hookee=hookee.cli:hookee
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - pluginbase
    - confuse
    - python-dotenv
    - flask
    - pyngrok

test:
  imports:
    - hookee
  commands:
    - pip check
    - hookee --help
  requires:
    - pip

about:
  home: https://github.com/alexdlaird/hookee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line webhooks, on demand
  description: |
    hookee is a simple command line utility which generates webhooks on demand and dumps useful information
    to the console when requests are sent to those endpoints.
  dev_url: https://github.com/alexdlaird/hookee

extra:
  recipe-maintainers:
    - alexdlaird
